Repository SonTonyD/Project-DNA, pull requests merged in 2022-12, with the labels that each got.

#2 Refactor: create PlayerManager
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/InputHandler.cs
  Assets/Scripts/PlayerManager.cs
  Assets/Scripts/PlayerManager.cs.meta
  Assets/Scripts/PlayerMovement.cs
Labels: refactor

#6 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#5 Create pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#7 Feature/dst/camera lock
  Assets/Materials/Enemy.mat
  Assets/Materials/Enemy.mat.meta
  Assets/PlayerControl.cs
  Assets/PlayerControl.inputactions
  Assets/Scenes/PlaygroundScene.unity
  Assets/Scenes/PlaygroundScene.unity.meta
  Assets/Scripts/AnimatorHandler.cs
  Assets/Scripts/CameraHandler.cs
  Assets/Scripts/CharacterManager.cs
  Assets/Scripts/CharacterManager.cs.meta
  Assets/Scripts/EnemyManager.cs
  Assets/Scripts/EnemyManager.cs.meta
  Assets/Scripts/InputHandler.cs
  Assets/Scripts/PlayerManager.cs
  Assets/Scripts/PlayerMovement.cs
  Assets/Shaders.meta
Labels: feature

#8 [Other] Various tweaks for demo
  .github/pull_request_template.md
  Assets/Materials/Ball.mat
  Assets/Materials/Enemy.mat
  Assets/Materials/Floor.mat
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/AnimatorHandler.cs
  Assets/Scripts/BasicRigidBodyPush.cs
  Assets/Scripts/CameraHandler.cs
  Assets/Scripts/EnemyManager.cs
  Assets/Scripts/InputHandler.cs
  Assets/Scripts/PlayerManager.cs
  Assets/Scripts/PlayerMovement.cs
Labels: refactor

#9 [Fix] Camera pivot height initialization on model not consistent
  Assets/Scripts/CameraHandler.cs
  Assets/Scripts/PlayerManager.cs
Labels: fix

#10 Fix/dst/double jump
  Assets/Characters/Animations/PlayerAnimator.controller
  Assets/Characters/Animations/PlayerAnimator.controller.meta
  Assets/Scenes/PlaygroundScene.unity
  Assets/Scripts/InputHandler.cs
  Assets/Scripts/PlayerManager.cs
  Assets/Scripts/PlayerMovement.cs
Labels: fix
